// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzt1WCAzFElvDJaaBNmQ0S2GREQESWX80',
    appId: '1:813433082673:web:9709afd3339af0f58b9610',
    messagingSenderId: '813433082673',
    projectId: 'school-wolrd',
    authDomain: 'school-wolrd.firebaseapp.com',
    databaseURL: 'https://school-wolrd-default-rtdb.firebaseio.com',
    storageBucket: 'school-wolrd.firebasestorage.app',
    measurementId: 'G-CXXJB1RYJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDLXkF0wpTcTdHMc-97x3EofH57iY09as',
    appId: '1:813433082673:android:cf6e8f056479c7ce8b9610',
    messagingSenderId: '813433082673',
    projectId: 'school-wolrd',
    databaseURL: 'https://school-wolrd-default-rtdb.firebaseio.com',
    storageBucket: 'school-wolrd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6PMz5L_r7Eh5-NVIbykRUUOKBYoT5fsk',
    appId: '1:813433082673:ios:db7c9811551480958b9610',
    messagingSenderId: '813433082673',
    projectId: 'school-wolrd',
    databaseURL: 'https://school-wolrd-default-rtdb.firebaseio.com',
    storageBucket: 'school-wolrd.firebasestorage.app',
    iosClientId:
        '813433082673-4ein9utmin4551tfhp7hd6om6kdosad2.apps.googleusercontent.com',
    iosBundleId: 'com.schoolworld.schoolWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6PMz5L_r7Eh5-NVIbykRUUOKBYoT5fsk',
    appId: '1:813433082673:ios:db7c9811551480958b9610',
    messagingSenderId: '813433082673',
    projectId: 'school-wolrd',
    databaseURL: 'https://school-wolrd-default-rtdb.firebaseio.com',
    storageBucket: 'school-wolrd.firebasestorage.app',
    iosClientId:
        '813433082673-4ein9utmin4551tfhp7hd6om6kdosad2.apps.googleusercontent.com',
    iosBundleId: 'com.schoolworld.schoolWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzt1WCAzFElvDJaaBNmQ0S2GREQESWX80',
    appId: '1:813433082673:web:472db80d3cc7bf4d8b9610',
    messagingSenderId: '813433082673',
    projectId: 'school-wolrd',
    authDomain: 'school-wolrd.firebaseapp.com',
    databaseURL: 'https://school-wolrd-default-rtdb.firebaseio.com',
    storageBucket: 'school-wolrd.firebasestorage.app',
    measurementId: 'G-WQRC6T1F5F',
  );
}
